# Provision GCP GKE cluster
apiVersion: xl-deploy/v1
kind: Infrastructure
spec:
- name: gke-blueprint-demo
  type: core.Directory
  children:
  - name: gcp-terraform
    type: overthere.LocalHost
    os: UNIX
    children:
    - name: terraform-client
      type: terraform.TerraformClient
      path: '/usr/local/bin' # for local installation
      workingDirectory: '/tmp/gke-blueprint-demo' # for local installation

---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: gke-blueprint-demo
  type: core.Directory
  children:
  - name: gcp-terraform
    type: udm.Environment
    members:
    - Infrastructure/gke-blueprint-demo/gcp-terraform
    - Infrastructure/gke-blueprint-demo/gcp-terraform/terraform-client